### ISSUE TITLE
Update the example yaml file

### ISSUE THREAD

**Issue by ArtemSokolov** [sorgerlab/rnaseq#13]
Here's an example file from the most recent RNAseq run with Luca: 

```
# Template for human RNA-seq using Illumina prepared samples
---
details:
  - analysis: RNA-seq
    genome_build: hg38
    algorithm:
      transcriptome_fasta:  /n/groups/sorger/Luca_Kyun_RNAseq/analysis/rnaseq/Homo_sapiens_dnarna/Homo_sapiens.GRCh38.allRCNA.fa
      transcriptome_gtf:  /n/groups/sorger/Luca_Kyun_RNAseq/analysis/rnaseq/Homo_sapiens_dnarna/Homo_sapiens.GRCh38.93.gtf
      aligner: hisat2
      strandedness: firststrand
      spikein_fasta:  /n/groups/sorger/Luca_Kyun_RNAseq/analysis/rnaseq/Homo_sapiens_dnarna/ERCC92/ERCC92.fa 
upload:
  dir: ../final
```

Need to update `yaml_O2.yaml` to incorporate these changes. Also need to update instructions that describe downloading the following reference files:

  *  ftp://ftp.ensembl.org/pub/release-93/fasta/homo_sapiens/ncrna/Homo_sapiens.GRCh38.ncrna.fa.gz
  * ftp://ftp.ensembl.org/pub/release-93/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz
  * ftp://ftp.ensembl.org/pub/release-93/gtf/homo_sapiens/Homo_sapiens.GRCh38.93.gtf.gz

the cDNA and ncRNA files should be merged together.

(The alternative is to download these files once, and to store them somewhere on O2 that the reference .yaml in this repo can access.)
